config/routes.rb
Rails.application.routes.draw do
  get 'order_sneakers/create'

  get 'order_sneakers/update'

  get 'order_sneakers/destroy'

  get 'carts/show'

  get 'pages/about' , as: :about

  get 'pages/contact' , as: :contact

  get 'sneakers/index'

  get 'sneakers/:id' , to: 'sneakers#show', as:'sneakers'

  root 'sneakers#index',  as: :home
  root to: "sneakers#index"

  resources :sneakers, only: [:index]
  resource :cart, only: [:show]
  resources :order_sneakers, only: [:create, :udpate, :destroy]

  #devise_for :sneakers, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :sneakers
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_sneakers
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    order_sneakers.collect { |os| os.valid? ? (os.quantity.to_i * os.price.to_f) : 0 }.sum
  end
  private
  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_sneaker.rb
class OrderSneaker < ApplicationRecord
  belongs_to :sneaker
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0}
  validate :sneaker_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      sneaker.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def sneaker_present
    if sneaker.nil?
      errors.add(:sneaker, "is not valid or is a trash ass shoe. ")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "your order is whack fam.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  belongs_to :brand
  has_many :order_sneakers
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :inventorys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_sneakers = current_order.order_sneakers
  end
end

app/controllers/order_sneakers_controller.rb
class OrderSneakersController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_sneakers.new(order_sneaker_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_sneaker = @order.order_sneakers.find(params[:id])
    @order_sneaker.update_attributes(order_sneaker_params)
    @orders_sneakers = @order.orders_sneakers
  end

  def destroy
    @order = current_order
    @order_sneaker = @order.order_sneakers.find(params[:id])
    @order_sneaker.destroy
    @order_sneakers = @order.order_sneakers
  end
  private
  def order_sneaker_params
    params.require(:order_sneaker).permit(:quantity, :sneaker_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @page = Page.find_by(title: "About")
    
  end

  def contact
    @page = Page.find_by(title: "Contact")
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  def index
  @sneakers = Sneaker.order("colorway").page(params[:page]).per(5)
  @order_sneaker = current_order.order_sneakers.new
  @search = if params[:term]
    Sneaker.where('model LIKE ?', "%#{params[:term]}%")
  else
    Sneaker.all
    end
    
  def show
    @sneaker = Sneaker.find(params[:id])
    # @sneaker = params[:number]
  end

  # def search_params
  #   #params.require(:sneaker[id]
  # end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_sneakers_helper.rb
module OrderSneakersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/carts/_cart_row.html.slim
.well
  .row
    .col-xs-8
      h4= sneaker.name
    .col-xs-4
      = form_for order_sneaker, remote: true do |f|
        h4.text-right
          | Unit Price:
          span style=("color: green") = number_to_currency order_sneaker.unit_price
        .row
          .col-xs-4
            = f.number_field :quantity, value: order_sneaker.quantity.to_i, class: "form-control", min: 1
            = f.hidden_field :sneaker_id, value: sneaker.id
          .col-xs-8.text-right
            .btn-group
              = f.submit "Update Quantity", class: "btn btn-primary"
              = link_to "Delete", order_sneaker, { data: { confirm: "Are you sure you wish to delete the product '#{order_sneaker.sneaker.model}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" }
        h4.text-right
          | Total Price:
          span style=("color: green") = number_to_currency order_sneaker.total_price

app/views/carts/_shopping_cart.html.slim
- if !@order_sneaker.nil? && @order_sneaker.errors.any?
  .alert.alert-danger
    ul
      - @order_sneaker.errors.full_messages.each do |msg|
        li= msg
- if @order_sneakers.size == 0
  p.text-center
    | There are no sneakers in your shopping cart.  Please #{link_to "go back", root_path} and add some kicks to your cart.
- else
  - @order_sneakers.each do |order_sneaker|
    = render 'carts/cart_row', sneaker: order_sneaker.sneaker, order_sneaker: order_sneaker, show_total: true

app/views/carts/show.html.slim
.shopping-cart
  = render "shopping_cart"

app/views/order_sneakers/create.js.erb
<% if @order.errors.any? || @order_sneaker.errors.any? %>
  alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_sneakers/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_sneakers/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/sneakers/_sneaker_row.html.slim
.well
  .row
    .col-xs-8
      h4= sneaker.model
    .col-xs-4
      = form_for order_sneaker, remote: true do |f|
        h4.text-right
          | Unit Price:
          span style=("color: green") = number_to_currency sneaker.price
        .input-group
          = f.number_field :quantity, value: 1, class: "form-control", min: 1
          .input-group-btn
            = f.hidden_field :sneaker_id, value: sneaker.id
            = f.submit "Add to Cart", class: "btn btn-primary"

app/views/sneakers/index.html.slim
h1 JSI
h2 Just Sneaker Inventory(s)
p This is your initial inventory! Use it to keep track of your sneaker collection

body
  / table#sneakers
  /   thead
  /     tr
  /      th Colorway
  /      th Brand
  /      th Model
  /      th Size
  /      th Condition
  /      th Release Date
  /      th Price
  /      th Quantity
  /   - @sneakers.each do | kicks |
  /     tr
  /       td = link_to kicks.colorway.to_s, sneakers_url(:id => kicks.id)
  /       td = kicks.brand
  /       td = kicks.model
  /       td = kicks.size
  /       td = kicks.condition
  /       td = kicks.release_date
  /       td = kicks.price
  /       td = kicks.quantity

p = link_to "About" , about_path
p = link_to "Contact" , contact_path

/ p = form_tag(search_path method:  :get ) do
/     = text_field_tag :term, params[:term]
/     = submit_tag 'Search' , name: nil
/     end

/ = paginate @sneakers

h3.text-center Products for Sale
.row
  .col-xs-6.col-xs-offset-3
    - @sneakers.each do |sneaker|
      = render "sneaker_row", sneaker: sneaker, order_sneaker: @order_sneaker

app/views/sneakers/show.html.slim
h1 Sneakers#show
p A more detailed view of your sneaker including pictures

h3
  | Nickname:
  =< @sneaker.colorway
h3
  | Brand:
  =< @sneaker.brand
h3
  | Model:
  =< @sneaker.model
h3
  | Size:
  =< @sneaker.size
h3
  | Condition:
  =< @sneaker.condition
h3
  | Release Date:
  =< @sneaker.release_date
h3
  | Price:
  =< @sneaker.price
h3
  | Image:
  = image_tag @sneaker.image.thumb